DEVICE_PATH := device/xiaomi/dew

# Device Identification
TARGET_DEVICE := dew
ALLOW_MISSING_DEPENDENCIES := true

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := generic
TARGET_CPU_VARIANT_RUNTIME := generic

# Bootloader & Display Configuration
TARGET_BOOTLOADER_BOARD_NAME := dew
TARGET_NO_BOOTLOADER := true
TARGET_SCREEN_DENSITY := 254

# Kernel & Header v4
BOARD_BOOTIMG_HEADER_VERSION := 4
BOARD_KERNEL_BASE := 0x80000000
BOARD_KERNEL_CMDLINE := bootopt=64S3,32N2,64N2
BOARD_KERNEL_PAGESIZE := 4096
BOARD_RAMDISK_OFFSET := 0x04000000
BOARD_KERNEL_TAGS_OFFSET := 0x0e000000
BOARD_KERNEL_IMAGE_NAME := Image
BOARD_INCLUDE_DTB_IN_BOOTIMG := true

TARGET_FORCE_PREBUILT_KERNEL := true
ifeq ($(TARGET_FORCE_PREBUILT_KERNEL),true)
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/kernel
TARGET_PREBUILT_DTB := $(DEVICE_PATH)/prebuilt/dtb.img
endif

# Partitions & Storage
BOARD_FLASH_BLOCK_SIZE := 131072
BOARD_BOOTIMAGE_PARTITION_SIZE := 67108864
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 67108864
BOARD_HAS_LARGE_FILESYSTEM := true
BOARD_SYSTEMIMAGE_PARTITION_TYPE := ext4
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
TARGET_COPY_OUT_VENDOR := vendor
TARGET_BOARD_PLATFORM := mt6768

# OrangeFox Recovery Flags
FOX_BUILD_TYPE := Unofficial
OF_MAINTAINER := impalyzy
FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER := true
OF_KEEP_FORCED_ENCRYPTION := true
OF_NO_TREBLE_COMPATIBILITY_CHECK := true
OF_DISABLE_MIUI_SPECIFIC_OVERRIDES := zero
OF_SCREEN_H := 1600
OF_STATUS_H := 80
OF_STATUS_INDENT_LEFT := 48
OF_STATUS_INDENT_RIGHT := 48
OF_USE_GREEN_LED := 0

# Backlight / Brightness configuration
TW_BRIGHTNESS_PATH := "/sys/class/leds/lcd-backlight/brightness"
TW_MAX_BRIGHTNESS := 4095
TW_DEFAULT_BRIGHTNESS := 2048

# Android 16 / SDK 36 Version and Security Patch Overrides
PLATFORM_VERSION := 16
PLATFORM_SECURITY_PATCH := 2026-12-31
VENDOR_SECURITY_PATCH := 2026-12-31
SDK_VERSION := 36
